### ISSUE TITLE
Error accessing API: openstack   obs container show

### ISSUE THREAD

**Issue by uvwild** [opentelekomcloud/python-otcextensions#114]
python-openstackclient  5.2.0   
otcextensions           0.9.1.dev6   

```
$ openstack obs container list -f yaml
- creation_date: '2020-10-06T21:35:04.895Z'
  name: mycontainername
```

but when trying to look further:
```
$ openstack obs container show mycontainername
Method Not Allowed: Client Error for url: https://obs.eu-de.otc.t-systems.com/, Method Not Allowed

```

**Comment by echomike80** [comment]
I have the same problem. :-(

openstackclient (4.0.0)
openstacksdk (0.52.0)
otcextensions (0.11.1)

**Comment by dcardozoo** [comment]
same here :( 
python-openstackclient (5.4.0)
otcextensions (0.12.0)

**Comment by anton-sidelnikov** [comment]
Currently didn't reproduced
otcextensions (0.19.0)
