### ISSUE TITLE
Please add new service CBR into it

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/python-otcextensions#130]
Would you please add this service into the extensions?

Release Notes: https://open-telekom-cloud.com/en/support/release-notes/cloud-server-backup-service/cbr-new-service

OTC Console View: https://console.otctest.t-systems.com/cbr/?region=eu-de#/cbr/manager/csbs/vaultList

Thank you
Robert

**Comment by tischrei** [comment]
I am just implementing the features of CBR into SDK. When this is finished, the client support will be started and later the Ansible modules as well. This will take some time, but the first PR for the resources has been started for review https://github.com/opentelekomcloud/python-otcextensions/pull/138

**Comment by anton-sidelnikov** [comment]
Last cbr resource implemented in #290, and available from 0.27.0 version
