### ISSUE TITLE
Document Database Service

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud/python-otcextensions#196]

**Comment by gtema** [comment]
Yes, need to be implemented

**Comment by anton-sidelnikov** [comment]
- [x] Datastores (#197)
- [x] Flavors (#200 )
- [x] Instances (#205 )
- [x] Cloud layer support (#209 )

**Comment by anton-sidelnikov** [comment]
https://github.com/opentelekomcloud/python-otcextensions/releases/tag/0.20.0
