### ISSUE TITLE
Simple Message Notification

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/python-otcextensions#20]
Implement `Simple Message Notification` service

- [x] Topic
  - [x] SDK
  - [x] CLI
  - [x] Docs
- [x] Subscription
  - [x] SDK
  - [x] CLI
  - [x] Docs
- [x] Template
  - [x] SDK
  - [x] CLI
  - [x] Docs
- [x] Message
  - [x] SDK
  - [x] CLI
  - [x] Docs
- [x] SMS
  - [x] SDK
  - [x] CLI
  - [x] Docs

**Comment by robert1x2** [comment]
fyi https://community.open-telekom-cloud.com/community?id=community_question&sys_id=2e5f5f6a13ed9c90d15ac969a6744128
