### ISSUE TITLE
func tests should not rely on count

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/python-otcextensions#201]
Some func tests (in particular https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/tests/functional/sdk/waf/v1/test_domain.py) is comparing amount of records it created. When we have orphans or multiple tests run in parallel this is not going to work. This things should be ripped out from the tests

**Comment by anton-sidelnikov** [comment]
Was fixed in https://github.com/opentelekomcloud/python-otcextensions/pull/200
