### ISSUE TITLE
Tag Management Service

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/python-otcextensions#24]
implement TMS

**Comment by robert1x2** [comment]
fyi - https://community.open-telekom-cloud.com/community?id=community_question&sys_id=17b7163713595890d15ac969a67441e5

**Comment by anton-sidelnikov** [comment]
https://docs.otc.t-systems.com/tag-management-service/api-ref/api_description/index.html - api docs

**Comment by RusselSand** [comment]
- [ ] resource tags
