### ISSUE TITLE
CCE: Get certificates from cluster

### ISSUE THREAD

**Issue by Excodibur** [opentelekomcloud/python-otcextensions#244]
There is an API for retrieving CCE certificates (https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0248.html) from OTC, but it does not seem to be supported by this library. 

Of course there are multiple ways to setup CCE programatically (this lib, Terraform, API directly), but the next crucial part in automating cluster setup would be to gain access to the cluster (aka setup kube-config) and deploy resources to it. For this the certificates need to be retrieved from CCE.

As it seems to be a very basic feature offered by all other major cloud-providers on the market, I am wondering if it was just missed to be implemented for the (main) OTC CLI tool. 

May I ask you to take a look at it? Perhaps I am missing something obvious here.

**Comment by gtema** [comment]
the sad obvious fact is that we missed to include this in docs: https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/cce/v3/_proxy.py#L130
You can even fetch this using Ansible modules: https://github.com/opentelekomcloud/ansible-collection-cloud/blob/master/plugins/modules/cce_cluster_cert_info.py

At the moment, however, there is no CLI implementation for that.
