### ISSUE TITLE
'AWSHTTPSConnection' object has no attribute 'ssl_context'

### ISSUE THREAD

**Issue by garloff** [opentelekomcloud/python-otcextensions#27]
When I use openstackclient with otcextensions, a lot of features work nicely.
However, once I try to use the s3 Object Storage, no service that I have not used before, works any longer.

To demonstrate this:
```
linux@test-std-opensuse-15-latest-ssh(00210/eu-de):~ [0]$ openstack
(openstack) obs container list
'AWSHTTPSConnection' object has no attribute 'ssl_context'
(openstack) server list
'AWSHTTPSConnection' object has no attribute 'ssl_context'
(openstack)
linux@test-std-opensuse-15-latest-ssh(00210/eu-de):~ [0]$ openstack
(openstack) server list
+--------------------------------------+--------------------------------------------+---------+----------------------------------------------------------------+-----------------------------------------------------+--------------------+
| ID                                   | Name                                       | Status  | Networks                                                       | Image                                               | Flavor             |
+--------------------------------------+--------------------------------------------+---------+----------------------------------------------------------------+-----------------------------------------------------+--------------------+
| 8ae4fcb8-1f01-4585-a670-e82976ca08d5 | TEST_Std_openSUSE_15_latest-ssh            | ACTIVE  | NET-66=192.168.66.68                                           | Standard_openSUSE_15_latest                         | s2.medium.1        |
[...]

```

**Comment by garloff** [comment]
https://github.com/boto/botocore/issues/1258
https://github.com/boto/botocore/pull/1466

I built botocore-1.11.1 which unvendored requests and boto3-1.9 for SUSE15, and this seems to improve things. obs container list now works.

Note: It's till strange that a broken boto3 would upone usage destroy other services.

**Comment by gtema** [comment]
I will soon replace boto3 with own implementation with deeper integration into the authorization process and hopefully this will not arise anymore

**Comment by gtema** [comment]
with issue #18 boto was replaced with own request signing plugin and "normal" "openstackSDK-native" implementation. Not all features are implemented as of now (i.e. ACL, versionins, etc), but basic features (list, create, delete, upload/download) are covered. The release will follow shortly
