### ISSUE TITLE
CCE v2

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/python-otcextensions#31]
implement CCE V2 api

**Comment by 28formica77** [comment]
Hi - just found the current extension only work with v1 as well. Is there a target for this update?

**Comment by gtema** [comment]
Yes, it is on the plan, but currently no concrete schedule. Upon need - during the next month

**Comment by lushanlushan** [comment]
Hi, is there any update about this issue?
Thank you.

**Comment by gtema** [comment]
Ok, I think in one week I can implement it.

----
typed from mobile, auto-correct typos assumed
----

**Comment by rul3m4k3r** [comment]
Any updates on the implementation?

**Comment by gtema** [comment]
ouch, got distracted last week. The branch 'next' contain the implementation. I would appreciate testing. If you need to have a pre-release - let me know. What is still missing is OpenStackClient bindings for the ccev2.

I will try to finish and merge it during this week.

**Comment by gtema** [comment]
I would appreciate testing of the ccev2 implementation. Basic tests are through.

Please reopen if you find issues
