### ISSUE TITLE
Openstack vpn missing

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/python-otcextensions#318]
Hi all,

i tried to create a vpn by using openstack cli but there is no command 

- openstack vpn 

available.

Will the command be available in a future release of the otcextensions ?

I am currently using version

- 0.28.2

Thanks in advance.

Best regards
Uli

**Comment by tischrei** [comment]
The APIs in Open Telekom Cloud are using the native OpenStack API for the VPN service.
You can use the openstack client out of the box to create or list VPN services. Of course, it is also possible to use it with otcextensions plugin installed, too.

As you can see in my example below, I am listing the vpns available in my project:


```
(installextensions) ubuntu@tino-dev ~> openstack --os-cloud otc vpn service list
+--------------------------------------+--------------------------------------+--------------------------------------+--------+--------+-------+----------------+
| ID                                   | Name                                 | Router                               | Subnet | Flavor | State | Status         |
+--------------------------------------+--------------------------------------+--------------------------------------+--------+--------+-------+----------------+
| <ID-VPN> | <NAME> | <Router-ID> | None   |        | True  | PENDING_CREATE |
+--------------------------------------+--------------------------------------+--------------------------------------+--------+--------+-------+----------------+

```


The param '--os-cloud otc' invokes the correct section of my clouds.yml configuration, so this is not important for you.

Please, let us know if the comment helps you and we can close the issue.

**Comment by hadoopch** [comment]
Which versions are you using ?

(ansible-env) [linux@sshjump-k1 cloudera_swissotc]$ openstack --version
openstack 6.0.0

It is missing in version 6.0.0

**Comment by tischrei** [comment]
```
(installextensions) ubuntu@tino-dev ~> pip freeze | grep otcextensions
otcextensions==0.28.2
(installextensions) ubuntu@tino-dev ~> pip freeze | grep openstack
openstackclient==4.0.0
openstackdocstheme==2.3.1
openstacksdk==0.100.0
python-openstackclient==5.4.0
```

**Comment by tischrei** [comment]
I updated everything and it is working. There seems to be an issue with dcs, but that doesn't matter for your case:

```
(installextensions) ubuntu@tino-dev ~> pip freeze | grep openstack
openstackclient==4.0.0
openstackdocstheme==2.3.1
openstacksdk==0.102.0
python-openstackclient==6.0.0
(installextensions) ubuntu@tino-dev ~> openstack --version
openstack 6.0.0
(installextensions) ubuntu@tino-dev ~> openstack --os-cloud otc vpn service list
Could not load 'dcs_instance_backup_restore': No module named 'otcextensions.osclient.dcs.v1.restore'
Could not load 'dcs_instance_restore_list': No module named 'otcextensions.osclient.dcs.v1.restore'
+--------------------------------------+--------------------------------------+--------------------------------------+--------+--------+-------+--------+
| ID                                   | Name                                 | Router                               | Subnet | Flavor | State | Status |
+--------------------------------------+--------------------------------------+--------------------------------------+--------+--------+-------+--------+
| <ID-VPN> | <NAME> | <Router-ID> | None   |        | True  | DOWN   |

```

**Comment by tischrei** [comment]
I suggest that you install the whole openstack environment in a virtuel env (venv) as it is described under: 
https://python-otcextensions.readthedocs.io/en/latest/install/pip_install.html#pip-installation-within-a-virtual-environment

...and use the commands after "sourcing" the environment. That ensures that the python packages are installed correctly and that there is no other pitfall with installed packages of your main system. So python then loads all commands out of your virtual env and the control of the installed components is much easier.

**Comment by hadoopch** [comment]
Thanks Tino

I did it according the recommendations on 

- https://python-otcextensions.readthedocs.io/en/latest/install/pip_install.html#pip-installation-within-a-virtual-environment

I found the reason it is provided by the python neutron client which is not installed when you do it according the mentioned web-page

-  pip3 install otcextensions python-openstackclient 

seems to be not enough to use all openstack commands. So the web page should be updated.

-  pip3 install otcextensions python-openstackclient  openstackclient

Best regards

Uli

**Comment by hadoopch** [comment]
Hi Polina,

i check the docs

https://python-otcextensions.readthedocs.io/en/latest/install/pip_install.html#pip-installation-within-a-virtual-environment


The web site still provides the incomplete pip command.

openstackclient   is missing !!!


Best regards

Uli
