### ISSUE TITLE
Tags from volumes are missing

### ISSUE THREAD

**Issue by dh-roland** [opentelekomcloud/python-otcextensions#342]
on "openstack server show $SERVERID|$SERVERNAME" the tags from server are shown.
on "openstack volume show $VOLUMEID|$VOLUMENAME" the tags form volume are missing.
Can the tags added to volume also?

**Comment by Polina-Gubina** [comment]
hi @dh-roland! Unfortunately, it is not possible to implement because openstack doesn't support tags for volumes
