### ISSUE TITLE
Classic Load Balancer

### ISSUE THREAD

**Issue by ebal** [opentelekomcloud/python-otcextensions#35]
Hello,

`openstack --os-cloud otc loadbalancer list`

returns only **Enhanced Load Balancers** 

Is there a way to manage (list/modify/delete/etc) **Classic Load Balancers** using otcextensions?

- https://python-otcextensions.readthedocs.io/en/latest/cli/load_balancer.html
- https://docs.otc.t-systems.com/en-us/api/elb/en-us_topic_0096561504.html

Thanks in advance,

**Comment by gtema** [comment]
Sorry for the late answer. As of now - no, it's not supported. Problem is that Classic LB is not OpenStack compatible and is managed through a different endpoint.

Do you have a chance to migrate to ELB? If not what exactly prohibits you?

**Comment by ebal** [comment]
Thanks for answering this question/issue.

As per my understanding otc-tools is now Archived (Deprecated) and otcextensions does not support Classic ELB, so is there an official supported tool (or perhaps a proposed migration guide) to automate the transition from Classic ELB to Enhanced ELB?

Thanks in advance.

**Comment by gtema** [comment]
I suggest you to first have a look on the comparison of the LBs under: https://docs.otc.t-systems.com/en-us/usermanual/elb/en-us_elb_01_0007.html and see, whether ELB fits your needs (what I expect to be the case). You might notice, that SSL is not marked as present - this is a documentation bug.
Anyway over there you might find lots of details about ELBs

**Comment by tischrei** [comment]
HI @ebal and @gtema ,

is this topic still relevant or can the ticket be closed?

**Comment by gtema** [comment]
Classic LB is being dropped from the platform, we need to focus on ELBv3 implementation instead
