### ISSUE TITLE
Which documentation is the correct one - readthedocs.io or otc-service.com?

### ISSUE THREAD

**Issue by EHJ-52n** [opentelekomcloud/python-otcextensions#354]
This repository is linking to

<https://docs.otc-service.com/python-otcextensions>

which provides details  about `otcextensions 0.25.1.dev7`. This "release" must be from the time after 12.01.2022  (tag [0.25.0](https://github.com/opentelekomcloud/python-otcextensions/releases/tag/0.25.0)) and before 04.02.2022 (tag [0.26.0](https://github.com/opentelekomcloud/python-otcextensions/releases/tag/0.26.0)) and is rather outdated.

There is another site offering documentation on the web:

<https://python-otcextensions.readthedocs.io/>

which provides details about `otcextension latest|0.30.3.dev2` which has no matching tag at all. But it seems to be up-to-date, as the latest tag [0.30.2](https://github.com/opentelekomcloud/python-otcextensions/releases/tag/0.30.2) is from 07.06.2023, hence, only two month old.

Switching to **stable** switches to 0.30.2, which is the latest available release.

It seems that the later site is the correct one.
Hence please update the website in the repository settings and provide a redirect from otc-service.com subdomain to the readthedocs.io one.

**Comment by anton-sidelnikov** [comment]
Hello @EHJ-52n this is actual now: https://python-otcextensions.readthedocs.io/, and later here https://docs.otc-service.com/python-otcextensions also will be actual version.

**Comment by Polina-Gubina** [comment]
@EHJ-52n  i think this https://docs.otc.t-systems.com/python-otcextensions/
