### ISSUE TITLE
"Missing value auth-url required for auth plugin password"

### ISSUE THREAD

**Issue by EHJ-52n** [opentelekomcloud/python-otcextensions#355]
If you are following the instructions from https://python-otcextensions.readthedocs.io/en/stable/install/configuration.html and receive the error message "Missing value auth-url required for auth plugin password", just add `--os-cloud otc` right after `openstack`. This will update the error message to `The username or password is wrong. (HTTP 401)` because you are using MFA and this is not documentation atm.

**Comment by anton-sidelnikov** [comment]
Answer in #356
