### ISSUE TITLE
How to connect to OTC via openstack with activated MFA

### ISSUE THREAD

**Issue by EHJ-52n** [opentelekomcloud/python-otcextensions#356]
Is there any way to use access keys or ask for MFA tokens while using this extension?

**Comment by Polina-Gubina** [comment]
hi! mfa is not recommended while using client, but this is the instructuion https://www.youtube.com/watch?v=JEniPHp1l74 how you can configure it

**Comment by Polina-Gubina** [comment]
@EHJ-52n  in case of further questions -just open new issue, feel free ask your questions
