### ISSUE TITLE
tags functionality in DWS SDK is not defined

### ISSUE THREAD

**Issue by vladimirhasko** [opentelekomcloud/python-otcextensions#366]
Please add the API for GET /v1.0/{project_id}/clusters/tags as currently this is being used also by cloudmon and the collected metric is mis-interpreted as /cluster

**Comment by anton-sidelnikov** [comment]
@Persimmonboy 
Look at: https://docs.otc.t-systems.com/data-warehouse-service/api-ref/api_description/tag_management_apis/querying_tags_in_a_specified_project.html
1. Need to add new class for Tags inside  SDK -> DWS -> V1 (reference: https://github.com/opentelekomcloud/python-otcextensions/blob/919c1f308b903b873fcae648aadcc04edb70e9ef/otcextensions/sdk/elb/v2/_base_tag.py)
2. Add proxy method
3. Unit test for class and proxy method
4. Functional test
Feel free to ask any help
