### ISSUE TITLE
Creating CCE node fails

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud/python-otcextensions#38]
I tried the following command to create an CCEv2 node and it fails:

 openstack --os-cloud otc cce cluster node create --flavor s2.large.8 --volume sata,'100' --root_volume sata,'40' --ssh_key my-pubkey-name my-cluster-name

The following output.
> create_cluster_node() missing 1 required positional argument: 'cluster'

**Comment by gtema** [comment]
Please try now and reopen if issue still persist
