### ISSUE TITLE
provide proper naming of swr metrics in sdk proxy as they are cut of to only 1st / level

### ISSUE THREAD

**Issue by vladimirhasko** [opentelekomcloud/python-otcextensions#403]
For queries like:

      - /manage/shared-repositories?center=self
      - /manage/repos
      - /manage/namespaces

When producing the metrics the otcextensions automatically cut of the part of the uri after 2nd "/" and all the different metrics are named samely "manage". Crete overwriting function which will customize the metric naming to be constructed by the strings after 2nd "/".

**Comment by anton-sidelnikov** [comment]
done
