### ISSUE TITLE
No otcextension for SWR

### ISSUE THREAD

**Issue by nahian166** [opentelekomcloud/python-otcextensions#405]
Hi there, 
We have to integrate CCE and SWR to the Apimon. But there are no ansible module for SWR. To build the ansible module first otcextension should support SWR. 
This is one of task for this PIP. 

Could you please develop simple module for SWR? I can provide some more information if needed.

**Comment by anton-sidelnikov** [comment]
work in progress

**Comment by anton-sidelnikov** [comment]
SDK for SWR available in latest version https://github.com/opentelekomcloud/python-otcextensions/releases/tag/0.31.0
