### ISSUE TITLE
DMS v2 sdk_proxy needed

### ISSUE THREAD

**Issue by petererdosi** [opentelekomcloud/python-otcextensions#407]
Hi!
We need an sdk_proxy for DMS v2 to integrate it with SD2, since this version is the recommended based on the documentation. (v1 is outdated, based on docs: https://docs.otc.t-systems.com/distributed-message-service/api-ref/)

Could you please develop this please?

**Comment by tischrei** [comment]
Can this issue be closed @anton-sidelnikov ?
I accidently came over and saw that a Merge has happened.

**Comment by anton-sidelnikov** [comment]
@tischrei  yes, sure
