### ISSUE TITLE
ENV vars and cloud.yaml keys for AK/SK are not standardized

### ISSUE THREAD

**Issue by dev00** [opentelekomcloud/python-otcextensions#43]
Hi,

currently the python-otcextensions requires
- in `clouds.yaml` `ak` and `sk` keys
- in env variables `S3_ACCESS_KEY_ID` and `S3_SECRET_ACCESS_KEY`
for interacting with various otc resources.

This is missleading from multiple perspectives:
1. the AK/SK pair is not limited to S3 or OBS
2. AWS uses `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` so `OS_ACCESS_KEY_ID` or `OS_SECRET_ACCESS_KEY` could be considered
3. terraforms [opentelekomcloud resource provider](https://www.terraform.io/docs/providers/opentelekomcloud/index.html#configuration-reference) uses `OS_ACCESS_KEY` and `OS_SECRET_KEY` from the env and `access_key` and `secret_key` inside the provider - imho the most elegant solution which could as well be used for the clouds.yaml

To avoid breaking backwards compatiblity I would recommend evaluating the terraform variables too and deprecate the `S3_*` env vars as well as the `ak` and `sk` inside `clouds.yaml` (issuing a warning), to remove it later.

What's your opinion on that?

EDIT: For some reason it looks like [this statement](https://github.com/OpenTelekomCloud/python-otcextensions/blob/master/otcextensions/sdk/__init__.py#L231) already pulls `OS_ACCESS_KEY` from the env - no idea why.

**Comment by gtema** [comment]
This was implemented historically as "backward-compatibility" for the old otc.sh tool. We might consider now dropping it, but likely better to support both. Actually terraform is not an indicator for us. On the other hand AK/SK are currently implemented in OTCE only for OBS, and not for other services.

**Comment by tischrei** [comment]
@gtema 
You have already merged a PR. Is this topic still relevant?
