### ISSUE TITLE
DNS zone list for type private does not work as expected

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud/python-otcextensions#430]
Related to the following customer request:
https://community.open-telekom-cloud.com/community?id=community_question&sys_id=4f9e57ecb786ce54d15aa7b16b8c02a1

The command:

`openstack --os-cloud otc dns zone list --type private`

does not work as expected. The response is provided properly, but the output from otcextensions fails.

Pls, fix the bug and update the user request accordingly.

**Comment by vladimirvshivkov** [comment]
getting error:
`'ZoneController' object is not callable`
