### ISSUE TITLE
Missing response parameters in SDK RDS v3 flavor.py

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud/python-otcextensions#470]
Need to update SKD  RDS v3 flavor.py
https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/rds/v3/flavor.py

Response parameter of the SDK does not provide all parameters as API response do. Especially "group_type" is missing.

API response:
![image](https://github.com/user-attachments/assets/b3159059-d68c-4b0a-94b6-fefdc26f4a53)

SDK response:
![image](https://github.com/user-attachments/assets/de1d5149-a29f-4e53-813e-94fda71204b9)

**Comment by vladimirhasko** [comment]
fix in https://github.com/opentelekomcloud/python-otcextensions/pull/471

**Comment by lboka** [comment]
I can confirm that the issue was fixed.  Thanks for the support.
![image](https://github.com/user-attachments/assets/ad49c6bf-40e7-4e75-bd95-b54bec82d092)

**Comment by lboka** [comment]
closing this issue now. Thanks.
