### ISSUE TITLE
Update for SDK RDS v3 with new API for Query Storage type

### ISSUE THREAD

**Issue by lboka** [opentelekomcloud/python-otcextensions#472]
I would like to request update for SDK RDS v3
https://github.com/opentelekomcloud/python-otcextensions/tree/master/otcextensions/sdk/rds/v3

I need to implement new API for Query Storage type in RDS service. This is currently missing in SDK.

Bellow is relevant information:
URI:  GET https://{Endpoint}/v3/{project_id}/storage-type/{database_name}?version_name={version_name}

API documentation:  https://docs.otc.t-systems.com/relational-database-service/api-ref/api_v3_recommended/querying_the_storage_type_of_a_database.html#rds-04-0002

**Comment by vladimirhasko** [comment]
fixed by PR: https://github.com/opentelekomcloud/python-otcextensions/pull/475
