### ISSUE TITLE
Openstack role list only returns built-in roles

### ISSUE THREAD

**Issue by Jaybee18** [opentelekomcloud/python-otcextensions#474]
I don't really know if this is in the scope of this project. If not, just close this issue.

When running
```sh
openstack role list
```
Only built-in roles are returned:
```sh
+----------------------------------+-----------------+
| ID                               | Name            |
+----------------------------------+-----------------+
| 04f313c749de42bba8f3081215be5819 | system_all_47   |
| 052dd2a25bca48d3a77b483df6440b52 | system_all_104  |
| 05dbc34ab3554d04913388e086c155ac | system_all_28   |
| 07cf80057bfe48c9980d3ecace8de19c | system_all_102  |
| 0b8f489d35fe42cca704da2220589cb3 | system_all_65   |
| 0c17da620e554bbca945da8bd369a09c | readonly        |
| 0d7fe9ed1c4840198fcb04a2c5aac465 | system_all_109  |
| 0dbf49c84c4444e0a69ced3e94cd3049 | dbss_sys        |

...

| f622024b0b904d90920b8e816c7bab88 | system_all_90   |
| f91ad60455764ea1b210d592f4c35372 | system_all_58   |
| fb5e567112984af8b3f85243742c5d9c | system_all_81   |
| fceb1e48f9054b6886bcc2b9c9fd2637 | system_all_75   |
| fed841e0f634475ca703f62574c214ff | system_all_39   |
+----------------------------------+-----------------+

```
 But I would like to also get the user-defined roles and policies.
The [example in the documentation](https://docs.openstack.org/keystone/ussuri//admin/cli-manage-projects-users-and-roles.html#:~:text=role%20assignments%C2%B6-,List%20available%20roles,-%C2%B6) suggests, that custom roles will also be listed.
Is this a mistake or am I using the cli wrong?

**Comment by anton-sidelnikov** [comment]
Hi @Jaybee18 the best would be to contact [service@open-telekom-cloud.com](mailto:service@open-telekom-cloud.com) and ask them what should be returned by this api call.

**Comment by sekoban** [comment]
@anton-sidelnikov @Jaybee18 

To my knowledge there are 2 APIs. Seems current implementation returns the "builtin" roles/policies (`/v3/roles`)
- [https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/permission_management/querying_a_role_list.html](https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/permission_management/querying_a_role_list.html)

But there is another one (`/v3.0/OS-ROLE/roles`), which returns the custom roles/policies
- [https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/custom_policy_management/listing_custom_policies.html#iam-02-0011](https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/custom_policy_management/listing_custom_policies.html#iam-02-0011)

**Comment by Jaybee18** [comment]
Hello @anton-sidelnikov and @sekoban,

Thank you for the response.
I am also aware of the v3-v3.0-endpoint-thing, I had to take it into account while developing our developer platform a few times.
I will write the service and ask them what this command should return according to them.

**Comment by anton-sidelnikov** [comment]
So, at least we know that v3.0 endpoints not covered by our sdk-cli, need to put it in our development plan.

**Comment by anton-sidelnikov** [comment]
Not yet released

**Comment by anton-sidelnikov** [comment]
Hi @Jaybee18, On latest version (0.32.1) of otce you can use:
`openstack iam custom role list`
