### ISSUE TITLE
Creating RDS Instance returns error

### ISSUE THREAD

**Issue by jcxxin** [opentelekomcloud/python-otcextensions#48]
**command line is:** 
(venv) [linux@centos-jiangchenxin-troubleshooting ~]$ openstack rds instance create --size 40 --users rdsuser:xxxxx --network_id 34572667-8b21-433d-838d-3f00037331b3  test_rds_jiangchenxin d8661205-929d-a263-6bca-e1100a64fa66

**Error message:**
'Proxy' object has no attribute 'find_flavor'
I found the find_flavor method is commented here:  https://github.com/OpenTelekomCloud/python-otcextensions/blob/master/otcextensions/sdk/rds/v1/_proxy.py

**Comment by tischrei** [comment]
Sorry for our late response,

Please use API version 3. There you can query the flavor list by using the recommended command 
`CLI: openstack rds flavor list <db_type> <db_version>`

or in SDK
```
flavors = conn.rds.flavors(datastore_name, version_name)
for flavor in flavors:
    print(flavor)
```
