### ISSUE TITLE
DNS recordset with more than 500 entries

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/python-otcextensions#85]
In the zone with >500 (default on the backend) recordsets backend does not return .links.next attribute in the response (but returns only first 500 results page), which is required to get to the next page. While the bug to the backend is filed, we need to ensure we try alternative way to get to the next page if we got less then .meta.total_count entries.

P.S. need to be done in the py2 branch also (centos 7 package required)

**Comment by tischrei** [comment]
https://github.com/opentelekomcloud/python-otcextensions/pull/89

**Comment by gtema** [comment]
closed with #89
