### ISSUE TITLE
Attributes for creating a CCE Cluster Node are wrong in example & docs

### ISSUE THREAD

**Issue by maawoo** [opentelekomcloud/python-otcextensions#88]
Hi there!
I just noticed that the example attributes for creating a node are wrong in the [examples](https://github.com/opentelekomcloud/python-otcextensions/blob/master/examples/cce/create_cluster_node.py) and the [docs](https://python-otcextensions.readthedocs.io/en/latest/sdk/guides/cce.html#create-cce-cluster-node) and were probably just copy pasted from the example to create a cluster.

As a minimal example it should look more like this:
```
attrs = {
    "kind": 'Node',
    "apiVersion": 'v3',
    "metadata": {
        "name": "test_node"
    },
    "spec": {
        "flavor": "s2.large.2",
        "az": 'eu-de-01',
        "login": {
            "sshKey": "KeyPair-Name"
        },
        "rootVolume": {
            "size": 40,
            "volumetype": "SATA"
        },
        "dataVolumes": [
            {
                "size": 100,
                "volumetype": "SATA"
            }
        ],
        "count": 1,
    }
}
```
... at least that worked for me ;)

It might also be a good idea to provide [this link](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0242.html#cce_02_0242__en-us_topic_0079616779_en-us_topic_0079614912_ref458774242) for more information about other parameters that can be provided.

**Comment by Nils-Magnus** [comment]
Indeed. Thanks for pointing out. @tischrei, could you have a look?

**Comment by maawoo** [comment]
No problem! 
I have a follow-up question related to those attributes: When creating a node with the OTC Console it's possible to define 'Maximum Data Space per Container' in the 'Advanced Kubernetes Settings'. Do you know if that's also possible in the attribute dictionary? Couldn't find anything [here](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0242.html), but I guess maybe in the extendParam field? Because that's also where maxPods is defined.

**Comment by gtema** [comment]
@tischrei , please have a look here after your vacation and do same what I did in #91 as introduction of cloud layer. We can move OSC logic for cluster creation there providing a reasonable flat interface, which is better usable and documentable

**Comment by tischrei** [comment]
For CCE Node creation the cloud layer interface has been introduced with the following commit: https://github.com/opentelekomcloud/python-otcextensions/commit/24becd2083b279337bbd872389e3ffa0391db0f2 .
